name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  push:
    branches:
      - main

jobs:
  # Existing build job remains the same
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: sprusrxeroxx
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  # New job for pushing to repository (optional)
  push-data:
    name: Push data to repository (Optional)
    runs-on: ubuntu-latest
    # Consider adding a separate workflow for pushing to avoid redundancy
    if: github.event.name == 'push' && github.base_branch == 'main'  # Only run on push to main branch
    steps:
      - uses: actions/checkout@v2  # Checkout the repository
      - name: Configure Git  # Configure Git user information (optional, adjust if needed)
        run: |
          git config --global user.email "ntokozovilakazi36@gmail.com"
          git config --global user.name "Ntokozo Vilakazi"
      - name: Add and commit changes  # Add any changes to be pushed 
        run: |
          git add .
          git commit -m "Update datas"
      - name: Push to repository 
        run: |
          git push https://${{ secrets.TOKEN }}@github.com/sprusrxeroxx/sprusrxeroxx.git
